name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  just-like-in-the-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        run: |
          rustup toolchain add ${{ matrix.rust }}
          rustup default ${{ matrix.rust }}
          rustup component add rustfmt
          rustup component add clippy
      - name: Check
        run: cargo check
      - name: Check code formatting
        run: cargo fmt --all --check
      - name: Clippy
        run: cargo clippy
      - name: Build
        run: cargo build --verbose --release
      - name: Test
        run: cargo test --verbose --release
