name: Rust Nightly

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  unstable-nightly-features:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-26.04, ubuntu-26.04-arm, macos-latest, windows-latest]
        rust: [nightly]
    steps:
      - uses: actions/checkout@v7
      - name: Set up Rust
        run: |
          rustup toolchain add ${{ matrix.rust }}
          rustup default ${{ matrix.rust }}
      - name: Build
        run: cargo build --verbose --features nightly
      - name: Test
        run: cargo test --verbose --features nightly
      - name: Build In Release Mode
        run: cargo build --verbose --features nightly --release
      - name: Test In Relase Mode
        run: cargo test --verbose --features nightly --release
